version: "3.7"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'study-plandb'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - studyplan_data:/var/lib/mysql
volumes:
  studyplan_data: