micronaut:
  application:
    name: studyPlan
datasources:
  default:
    url: jdbc:mysql://localhost:3306/study-plandb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update


jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
  serialization-inclusion: non_absent
